AWSTemplateFormatVersion: "2010-09-09"
Description: ---main stack
Metadata:
    AWS::Cloudformation::Interface:
      ParameterGroup:
      - Label:
          default: Network Settings
        Parameters:
          - VpcId
          - PSubnet1
          - PSubnet2
          - Subnet1
          - Subnet2
      - Label:
          default: Cfn Bucket Name
        Parameters:
          - bucketName
      - Label:
          default: Applilcation Layer Settings
        Parameters:
          - BaseAMI
          - WebInstanceType
          - WebAsgMin
          - WebAsgMax
          - Key

      ParameterLabels:
       VpcId:
         default: The Vpc ID where this stack deploy
       bucketName:
         default: where you upload your cfn
       Psubnet1:
         default: Public subnet 1 for ALB
       Psubnet2:
         default: Public subnet 2 for ALB
       subnet1:
         default: private subnet 1 which web server launching in
       subnet2:
         default: private subnet 2 which web server launching in
       BaseAMI:
         default: Base AMI which will using by Web server
       WebInstanceType:
         default: moodle server size
       WebAsgMin:
         default: Specifies the minimum number of EC2 instances in the Web Autoscaling Group
       WebAsgMax:
         default: Specifies the maximum number of EC2 instances in the Web Autoscaling Group
       Key:
         default: ec2 key
Parameters:

  VpcId:
    Description: Vpc Id
    Type: String

  bucketName:
    Description: BucketName
    Type: String

  Psubnet1:
    Description: Public SubnetID
    Type: String
  Psubnet2:
    Description: Public SubnetID
    Type: String

  subnet1:
    Description: Private SubnetID
    Type: String
  subnet2:
    Description: Private SubnetID
    Type: String
  BaseAMI:
    Description: ami id
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  WebAsgMin:
    Description: min number in asg
    Type: String
    Default: 1
  WebAsgMax:
    Description: min number in asg
    Type: String
    Default: 1
  KeyPairs:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the key to deploy for the stack

  WebInstanceType:
    Description: ami id
    Type: String
Resources:

  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
         VpcId:
           !Ref VpcId
         Psubnet1:
           !Ref Psubnet1
         Psubnet2:
           !Ref Psubnet2

      TemplateURL:
           !Sub
              - https://s3-ap-southeast-2.amazonaws.com/${bucketName}/1_ALB_layer.yaml
              - { bucketName: !Ref bucketName }


  ServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Vpcid:
          !Ref VpcId
        Subnet1:
          !Ref subnet1
        Subnet2:
          !Ref subnet2
        AMI:
          !Ref BaseAMI
        Key:
          !Ref KeyPairs
        InstanceSize:
          !Ref WebInstanceType

        TargetGroupArns:
          !GetAtt [ALBStack,Outputs.albTargetGroup]
        MaxSize:
          !Ref WebAsgMax
        MinSize:
          !Ref WebAsgMin
        ElbSG:
          !GetAtt [ALBStack,Outputs.ElbSG]
      TemplateURL:
          !Sub
          - https://s3-ap-southeast-2.amazonaws.com/${bucketName}/2_Service_layer.yaml
          - { bucketName: !Ref bucketName }


