AWSTemplateFormatVersion: 2010-09-09
Description: AL substack

Parameters:

  Psubnet1:
    Description: subnet 1
    Type: String
  Psubnet2:
    Description: subnet 2
    Type: String
  VpcId:
    Description: vpc id
    Type: String

Resources:
   albListener:
      Type : AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref albTargetGroup
        LoadBalancerArn: !Ref alb
        Port: 80
        Protocol: HTTP
   albTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
       HealthCheckIntervalSeconds: 60
       HealthCheckPath: /
       HealthCheckTimeoutSeconds: 5
       Name: !Join [ '', [ 'AP-', !Ref VpcId ] ]
       Port: 9292
       Protocol: HTTP
       Tags:
       - Key: StackName
         Value: rea
       UnhealthyThresholdCount: 5
       HealthyThresholdCount: 2
       VpcId: !Ref VpcId
   alb:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Scheme: internet-facing
        Subnets:
          - !Ref Psubnet1
          - !Ref Psubnet2
        LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 60
        SecurityGroups:
        - !Ref Elbsg
        Tags:
        - Key: StackName
          Value: rea
   Elbsg:
       Type: AWS::EC2::SecurityGroup
       Properties:
         GroupDescription: elb SG
         VpcId: !Ref VpcId
         SecurityGroupIngress:
           - IpProtocol: tcp
             FromPort: 80
             ToPort: 80
             CidrIp: 0.0.0.0/0
             Description: web access
         Tags:
           - Key: StackName
             Value: rea


Outputs:
  ElbSG:
    Value: !GetAtt Elbsg.GroupId

  alburl:
    Description: endpoint for alb
    Value: !GetAtt alb.DNSName
  albTargetGroup:
    Description: alb target arn
    Value: !Ref albTargetGroup

