AWSTemplateFormatVersion: 2010-09-09
Description: --sub stack for service

Parameters:

    AMI:
      Description: The application base AMI which default will be Amazon linux
      Type: String
    Vpcid:
      Description: Vpc id
      Type: String

    InstanceSize:
      Description: the instance type which using for runing moodle application
      Type: String
      Default: t3.medium

    Subnet1:
      Description: subnet1
      Type: String
    Subnet2:
      Description: subnet1
      Type: String

    ElbSG:
      Description: ELb sg id
      Type: String

    TargetGroupArns:
      Description: tg arn
      Type: String

    MaxSize:
      Description: Max size of Auto-Scaling
      Type: Number

    MinSize:
      Description: Min Size of Auto Scaling
      Type: Number
    Key:
      Description: EC2 key
      Type: String


Resources:
    ServerProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Path: /
        Roles:
          - !Ref Role
    Role:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: log
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogStreams
                    - cloudformation:SignalResource
                  Resource: "*"

    logs:
      Type: AWS::Logs::LogGroup
      DeletionPolicy: Retain
      Properties:
        RetentionInDays: 7
    webSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: ELB moodle SG
        VpcId: !Ref Vpcid
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 9292
            ToPort: 9292
            SourceSecurityGroupId: !Ref ElbSG
            Description: Allow traffic from elb
    AutoScalingGroup:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        Cooldown: 60
        HealthCheckGracePeriod: 120
        HealthCheckType: ELB
        LaunchConfigurationName: !Ref LaunchConfig
        MaxSize: !Ref MaxSize
        MinSize: !Ref MinSize
        Tags:
          -
           Key: StackName
           Value: rea
           PropagateAtLaunch: true
        TargetGroupARNs:
          - !Ref TargetGroupArns
        VPCZoneIdentifier:
          - !Ref Subnet1
          - !Ref Subnet2
    LaunchConfig:
      Type: AWS::AutoScaling::LaunchConfiguration
      Properties:
        IamInstanceProfile: !Ref ServerProfile
        ImageId: !Ref AMI
        InstanceMonitoring: true
        InstanceType: !Ref InstanceSize
        KeyName: !Ref Key
        SecurityGroups:
           - !Ref webSG
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -ex

            #install git 
            yum install git -y

            #update ruby 
            curl -sSL https://get.rvm.io | bash
            source /etc/profile.d/rvm.sh
            rvm install "ruby-2.4.9"

            # install dependendies
            gem install bundle
            

            # download app code and run
            cd /opt/
            sudo git clone https://github.com/rea-cruitment/simple-sinatra-app
            cd simple-sinatra-app
            bundle install
            bundle exec rackup


